steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/warsaw-tram-platform/tram-platform/prediction-api:latest', '-f', 'prediction_api/Dockerfile', '.']

images:
  - 'europe-central2-docker.pkg.dev/warsaw-tram-platform/tram-platform/prediction-api:latest'