FROM gcr.io/dataflow-templates-base/python312-template-launcher-base:latest

WORKDIR /app

COPY stream_processor/requirements.txt /app/stream_processor/requirements.txt

COPY shared/ /app/shared/
COPY stream_processor/ /app/stream_processor/

ENV PYTHONPATH=/app
ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/app/stream_processor/pipeline.py"
ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE="/app/stream_processor/requirements.txt"

ENTRYPOINT ["/opt/google/dataflow/python_template_launcher"]