FROM gcr.io/dataflow-templates-base/python311-template-launcher-base:latest

WORKDIR /app

COPY stream_processor/requirements.txt /app/stream_processor/requirements.txt
COPY shared/ /app/shared/
COPY stream_processor/ /app/stream_processor/

RUN pip install --no-cache-dir -r /app/stream_processor/requirements.txt

ENV PYTHONPATH=/app
ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/app/stream_processor/pipeline.py"

ENTRYPOINT ["/opt/google/dataflow/python_template_launcher"]